/**
 * build.js — inlines every module and the stylesheet into one self-contained
 * HTML file at dist/budget.html.
 *
 * Why: the modular source needs a web server (ES modules are blocked on
 * file://). The bundle opens by double-click on Windows and can be dropped
 * onto a phone or emailed to yourself. Same code, same behaviour.
 *
 *   node build.js
 */

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(fileURLToPath(import.meta.url));
const ENTRY = 'js/app.js';

/* ---------- resolve the module graph, depth-first ---------- */

const seen = new Set();
const order = [];

const IMPORT_RE = /^\s*import\s+(?:[\s\S]*?)\s+from\s+['"](\.[^'"]+)['"]\s*;?\s*$/gm;
const BARE_IMPORT_RE = /^\s*import\s+['"](\.[^'"]+)['"]\s*;?\s*$/gm;
const EXPORT_FROM_RE = /^\s*export\s+(?:[\s\S]*?)\s+from\s+['"](\.[^'"]+)['"]\s*;?\s*$/gm;

async function walk(relPath) {
  const abs = resolve(ROOT, relPath);
  if (seen.has(abs)) return;
  seen.add(abs);

  const src = await readFile(abs, 'utf8');
  const deps = new Set();
  for (const re of [IMPORT_RE, BARE_IMPORT_RE, EXPORT_FROM_RE]) {
    re.lastIndex = 0;
    let m;
    while ((m = re.exec(src)) !== null) {
      if (!m[1].startsWith('http')) deps.add(m[1]);
    }
  }
  for (const d of deps) {
    await walk(join(dirname(relPath), d).split('\\').join('/'));
  }
  order.push({ relPath, src });
}

/* ---------- strip module syntax so everything shares one scope ---------- */

function flatten(src) {
  return src
    // drop relative imports entirely — the modules are concatenated in order
    .replace(/^\s*import\s+[\s\S]*?\s+from\s+['"]\.[^'"]+['"]\s*;?\s*$/gm, '')
    .replace(/^\s*import\s+['"]\.[^'"]+['"]\s*;?\s*$/gm, '')
    .replace(/^\s*export\s+[\s\S]*?\s+from\s+['"]\.[^'"]+['"]\s*;?\s*$/gm, '')
    // `export const x` -> `const x`, `export function f` -> `function f`
    .replace(/^\s*export\s+(default\s+)?(?=(const|let|var|function|class|async)\b)/gm, '')
    // drop re-export statement lists: `export { a, b };`
    .replace(/^\s*export\s*\{[^}]*\}\s*;?\s*$/gm, '');
}

/* ---------- emit ---------- */

const html = await readFile(resolve(ROOT, 'index.html'), 'utf8');
const css = await readFile(resolve(ROOT, 'css/styles.css'), 'utf8');
await walk(ENTRY);

const banner = `/* Budget — single-file build, generated ${new Date().toISOString()}.
   Do not edit: change the modules in js/ and re-run \`node build.js\`. */`;

const js = [banner, ...order.map((m) => `\n/* ---- ${m.relPath} ---- */\n${flatten(m.src)}`)].join('\n');

const out = html
  .replace('<link rel="stylesheet" href="css/styles.css">', `<style>\n${css}\n</style>`)
  .replace('<link rel="manifest" href="manifest.json">', '')
  .replace('<script type="module" src="js/app.js"></script>', `<script type="module">\n${js}\n</script>`);

await mkdir(resolve(ROOT, 'dist'), { recursive: true });
await writeFile(resolve(ROOT, 'dist/budget.html'), out, 'utf8');

/* ---------- artifact variant ----------------------------------------
 * Hosted pages supply their own <!doctype>/<head>/<body>, and their theme
 * toggle stamps data-theme on the root element — which must beat the
 * prefers-color-scheme media query in BOTH directions. Because every
 * theme-varying value is a token on :root, both overrides can be generated
 * from the stylesheet instead of duplicating component CSS by hand.
 * ------------------------------------------------------------------ */

function rootVars(source, { dark = false } = {}) {
  const re = dark
    ? /@media \(prefers-color-scheme: dark\) \{\s*:root \{([\s\S]*?)^ {2}\}/m
    : /^:root \{([\s\S]*?)^\}/m;
  const m = source.match(re);
  if (!m) throw new Error(`build: could not extract ${dark ? 'dark' : 'light'} :root tokens`);
  return m[1].trim();
}

const themeBlocks = `
/* ---- generated by build.js: the host's theme toggle must win over the OS ---- */
:root[data-theme="light"] {
${rootVars(css)}
}
:root[data-theme="dark"] {
${rootVars(css, { dark: true })}
}
`;

// No service worker on a hosted page — there is no scope to register against.
const artifactJs = js.replace(
  /if \('serviceWorker' in navigator\) \{[\s\S]*?\n\}/,
  '/* service worker omitted in the hosted build */'
);

const artifact = `<title>Budget — 15th to 14th</title>
<style>
${css}
${themeBlocks}
</style>

<div id="root"></div>

<script type="module">
${artifactJs}
</script>
`;

await writeFile(resolve(ROOT, 'dist/budget-artifact.html'), artifact, 'utf8');

console.log(`dist/budget.html           ·  ${order.length} modules  ·  ${(out.length / 1024).toFixed(1)} KB`);
console.log(`dist/budget-artifact.html  ·  hosted build     ·  ${(artifact.length / 1024).toFixed(1)} KB`);
for (const m of order) console.log(`  ${m.relPath}`);
